### PR TITLE
Update to fix issue #47

### PR DESCRIPTION
**Pull request by stephen110**
Solves the problem seen in issues #47 and #44 while still allowing component to manage its state during resizing.

### CODE REVIEW

**Comment by JoaoMosmann** [comment]
#44 is a PR. and  #47 specifies that the component is ResizableBox. Your changes are applied to the Resizable component, which doesn't solve the issue #47

**Comment by stephen110** [comment]
Yep, sorry, I have no idea why I referenced #44 - I'll update the title.  The update should solve the issue you were seeing in #47, while also applying that fix to Resizable in general.  

The issue is that height/width props can be updated during a resize.  The Resizable components props will update, but the components state will essentially ignore the sizing props passed in if the props passed during resizing are the same as those passed after resizing is done.

**Comment by JoaoMosmann** [comment]
Yes, it fixes the problem if you're using the Resizable Component, which is not the case of the issue #47 where the component being used is the ResizableBox. 

The ResizableBox component doesn't have a `componentWillReceiveProps` method. On the #44, I added this method to fix the problem. But it still not merged.

**Comment by stephen110** [comment]
Make sense, and you are absolutely correct about the behavior of ResizableBox.  I needed the fix for Resizable, and didn't see that width/height on the wrapped Resizable within ResizableBox comes from that components state, not from props.

So my PR doesn't fix your issue, but applies the same fix to Resizable.

**Comment by STRML** [comment]
This will break most usage of `<Resizable>`; for example:

* `<Resizable>` mounts at 100x100
* User resizes to 150*150
* Component updates for some other reason 
* `state.x !== nextProps.x`, `state.y !== nextProps.y`
* `<Resizable>` incorrectly resizes back to 100x100.

**Comment by stephen110** [comment]
Gotcha, I may have an outlier use case, but my size state is managed externally from the Resizable component.  So on resize, parent state changes, and that state is passed as props to the Resizable component.  It sounds like height/width props true intentions are initialHeight/initialWidth.

If that sounds right, I can revisit how this could be implemented without breaking legacy users.

**Comment by STRML** [comment]
Your use case sounds like it should work just fine with the existing code.

I agree that they're more of `initial*` props. Unfortunately, allowing parents to override state is a difficult pattern. The best solution I know of is to take the same approach React inputs take; you have `controlled` and `uncontrolled` modes.

**Comment by JoaoMosmann** [comment]
Now I get it. It would be a breaking change. Existing code using the library might bug if they don't treat their state correctly.

So to implement a `controlled` and `uncontrolled` mode the resizable component should have 2 sets of size properties. Something like `initialWidth and initialHeight` and `width and height`. However, this way it would be a breaking change too, as the initialWidth would have the old width behavior and the width would be new.

Maybe a `controlledWidth and controlledHeight`. Keeping `width and height` as initial values.

Tricky.

**Comment by STRML** [comment]
Yes, this would be breaking unless we shuffled the param names. It would be nice to not break backcompat but I'd like to take a stance on this more similar to how React input elements work as not to break expectation.

**Comment by JoaoMosmann** [comment]
There is an alternative way. I honestly don't like it. But it might work. It keeps backcompat, but it's not as react handle inputs.

Use a reference to update the width/height

```
  update() {
    this.resizable.updateSize({ width: 200, height: 300 });
  }

  render() {
    return (
      <ResizableBox ref={c => { this.resizable = c; }}>
        example
      </ResizableBox>
    );
  }
```

**Comment by STRML** [comment]
Yeah, you can always set the state yourself that way so that should even
work without modification. It's just dirty.

**Pull request closed without merging**
