### PR TITLE
Custom resize handle

### PR DESCRIPTION
**Pull request by cheton**
This PR provides support for customizing the resize handle in addition to the default handle:
`<span className="react-resizable-handle" />` .

### CODE REVIEW

**Comment by Jordan-Bortolotti** [comment]
👍

**Comment by grayrattus** [comment]
Will this be merged? @STRML

**Comment by STRML** [comment]
Yeah, this is good, thanks @cheton!

**Comment by STRML** [comment]
Yeah, this is good, thanks @cheton!

**Comment by arfeo** [comment]
And what about documenting the new feature?

**Pull request merged**
