### PR TITLE
update bounds on componentWillReceiveProps

### PR DESCRIPTION
**Pull request by ayozebarrera**
I opened a issue about re-render with different width and height causing error about bounds state.
I think with this line that will be resolved. Tell me if I'm wrong.

### CODE REVIEW

**Comment by STRML** [comment]
Could you post an example of where the current behavior breaks down?

**Comment by ayozebarrera** [comment]
I'm using React DnD, and one of his features is Custom drag PREVIEW. Inside of this DnD I have a Resizable component.

How it works? If you drag, the current component will return false and will appear a "clone" and when you stop of dragging, your component will be back.

So.. if I resize and then do the drag the initialHeight and initialWidth is updated but not the bounds.. 

Example:
If we have a resizable with 400 of width, and minConstrants are [200,200]... We have the left bound at -200.. right?
If a resize it to 200 and then re-render the component (with the dragging) the initialWidth will be 200, and his bounds still the same.. -200 so I can resize this to < 200 :(

Updating the code if its re-render, the bounds will be updated and will be 0. So we can't resize it anymore to < 200.

**Comment by ayozebarrera** [comment]
Do you see any wrong on this?

**Comment by ayozebarrera** [comment]
@STRML What do you think about my "case"?

**Comment by ayozebarrera** [comment]
Still waiting...

I need your response because if you are not going to merge this, I'll need fork the project.

**Comment by STRML** [comment]
I'll merge it. Thanks for the contribution and sorry for taking so long to get back to you. I am planning on soon finishing a rewrite of <Draggable>.

**Comment by ayozebarrera** [comment]
I'm not in a hurry and now that I know that you're going to merge it I won't worry anymore.
Sorry for all the questions I did but was important :)

so.. cool! thankyou~

**Pull request merged**
