### PR TITLE
Inline style

### PR DESCRIPTION
**Pull request by zillding**
a) use inline css for styling so no additional css file is required
b) keep the class name of the element to allow backward compatibility

### CODE REVIEW

**Comment by andela-aabdulwahab** [comment]
@zillding Please review the conflicts associated with this PR so it can be merged. It's a very useful addition to the module, I was planning to do this before I saw your PR.

**Comment by zillding** [comment]
@andela-aabdulwahab Thanks for your interest. It has been such a long time that I have forgotten about this.

As you can see the original author of this module @STRML has moved quite ahead, I am not sure whether this feature is wanted or not. I respect the original author's intention.

**Comment by STRML** [comment]
Yes, I am not in favor of littering the DOM with these inline styles. I have seen other projects (namely material-ui) attempt this and it has caused all manner of issues.

Doing so would break backcompat in various ways, including requiring users to use `!important` to override any default style. Therefore I don't intend to merge this.

You are free to add these styles yourself to the components you wrap, or simply include the CSS.

**Comment by zillding** [comment]
@STRML 👍  Good point. Thanks for your feedback.

**Comment by andela-sdamian** [comment]
👍

**Pull request closed without merging**
